added some controller routes for more item types
rhysrfrazier/FrazierKnivesFull pull request #10
Opened 2024-04-11 19:00 UTC by rhysrfrazier

2024-04-13 14:29 UTC, WrylyRiley requested changes

2024-04-13 14:29 UTC, WrylyRiley commented on server/controllers/itemController.js
> +async function getBracelets (req, red) {
I think this is a typo?
```suggestion
async function getBracelets (req, res) {
```

2024-04-13 14:29 UTC, WrylyRiley commented on server/controllers/itemController.js
> +async function getPottery (req, red) {
This too 
```suggestion
async function getPottery (req, res) {
```

2024-04-18 14:34 UTC, rhysrfrazier commented on server/controllers/itemController.js
> +async function getPottery (req, red) {
oh my god. yes it is, thank you

2024-04-18 14:40 UTC, WrylyRiley approved these changes

2024-04-18 15:18 UTC, merged